.PHONY: all part1 part2 part3 part4 part5 part6 clean

all: part1 part2 part3 part4 part5 part6

part1:
	$(MAKE) -C Part1

part2:
	$(MAKE) -C Part2

part3:
	$(MAKE) -C Part3

part4:
	$(MAKE) -C Part4

part5:
	$(MAKE) -C Part5

part6:
	$(MAKE) -C Part6

clean:
	$(MAKE) -C Part1 clean
	$(MAKE) -C Part2 clean
	$(MAKE) -C Part3 clean
	$(MAKE) -C Part4 clean
	$(MAKE) -C Part5 clean
	$(MAKE) -C Part6 clean
